openapi: 3.0.0
info:
  title: Sample API
  version: 0.0.1
servers:
  - url: http://127.0.0.1:5000/api/v1
    description: api for sqlalchemy
paths:
  "/students":
    get:
      summary: Returns a list of students.
      description: Optional extended description in CommonMark or HTML.

      parameters:
        - name: page
          in: path
          required: false
          schema:
            type: integer
            format: int

      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            {"name": 'testName', ""}


#  "/students":
#    post:
#      summary: post student in database
#      description: Optional extended description in CommonMark or HTML.
#      responses:
#        '200': # status code
#          description: A JSON array of user names
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  type: string
#